### ISSUE TITLE
Attributes don’t start multiline input in evcxr_repl

### ISSUE THREAD

**Issue by GoldsteinE** [evcxr/evcxr#219]
**How to reproduce:**

1. Start `evcxr` binary
2. Enter `#[derive(Debug)]`

**Expected behaviour:**

REPL enters multiline mode to allow writing an item definition.

**Actual behaviour:**

REPL tries to execute this line on it’s own, resulting in compilation error.

**Comment by davidlattimore** [comment]
Thanks for the report. You can workaround this by putting the derive on the same line as the rest of the item.

If you or anyone else wanted to have a go at fixing this, look for the function `validate_source_fragment`.
