### ISSUE TITLE
Cannot connect to rust kernel from a jupyter server in a conda env

### ISSUE THREAD

**Issue by AngryMaciek** [evcxr/evcxr#222]
I have been trying to install a Rust kernel for a Jupyter server inside a dedicated conda environment but I get errors:

1. `conda create -n rusttest`
2. `conda activate rusttest`
3. `conda install -c conda-forge rust jupyterlab`
4. `conda install -c anaconda cmake -y`
5. `cargo install evcxr_jupyter`
6. Add `$HOME/.cargo/bin` to my PATH variable (export PATH)
7. `evcxr_jupyter --install` (here I already see the kernel is installed outside the env)
8. `jupyter lab`

The kernel is visible on the dashboard however when I try to start a notebook with it the connection fails and I get:
> Error: Failed to find sysroot for Cargo.toml file /tmp/.tmpbZ0Pkw/Cargo.toml. Is rust-src installed?

I have tried manually:
```
jupyter kernelspec install {MY_PATH_DURING_PKG_INSTALLATION}/Jupyter/kernels/rust --sys-prefix
```
And I get:
```
[InstallKernelSpec] Installed kernelspec rust in {MY_PATH}/miniconda3/envs/rusttest/share/jupyter/kernels/rust
```
Which seems OK (inside the correct conda env) but the error persists.

Is there any way to add the kernel just to this one jupyter server inside that env?  
(I want Rust to be gone when I start `jupyter lab` from another conda env)

**Comment by bjorn3** [comment]
Evcxr needs the rust-src rust component which contains the source code of the standard library. It doesn't seem like conda provides any way to install it. You will probably have more luck with using rustup instead of conda for managing your rust installation.

**Comment by AngryMaciek** [comment]
_conda_ for package management is our priority, this will not change as we use many other software packages, not just rust-specific.

Is there any workaround to install it properly, then? Would be very useful since Anaconda environments are quite popular in data science community.

**Comment by bjorn3** [comment]
You will probably have to ask conda to package it.

**Comment by AngryMaciek** [comment]
@bjorn3: this is not how things work. Anaconda does not package custom packages of others. It's a responsibility of the developers to package their tool and upload it to Anaconda Cloud themselves, either to their own channels or `conda-forge` (even better).

@davidlattimore: would you know of any workaround?

**Comment by bjorn3** [comment]
I mean ask whoever maintains the rust package to add rust-src. https://anaconda.org/conda-forge/rust doesn't list who the maintainers of this package are.

**Comment by bjorn3** [comment]
Found it: https://github.com/conda-forge/rust-feedstock

**Comment by AngryMaciek** [comment]
In this case the problem is really somewhere downstream on the line jupyter-in-conda vs. rust-kernel. (i.e. this repo)

Please take a look at their README, they specify installation instructions with `conda`.
I have these packages installed in my environment and still I get the error as above.

```
$ conda list | grep "rust"
# packages in environment at XXXXX/miniconda3/envs/rusttest:
rust                      1.61.0               h7e1429e_0    conda-forge
rust-std-x86_64-apple-darwin 1.61.0               h059895a_0    conda-forge
```

**Comment by bjorn3** [comment]
> Or did I misunderstand you, did you mean that rust-src is not a part of the feedstock package<?>

Indeed. I checked that already by downloading https://anaconda.org/conda-forge/rust/1.61.0/download/linux-64/rust-1.61.0-h30be4a0_0.tar.bz2 and checking if the `lib/rustlib/src/rust` directory is present.

You can also check it yourself using

```
$ ls $(rustc --print sysroot)/lib/rustlib/src/rust
```

If rust-src is present, it will show

```
Cargo.lock  library  src
```

If not, it will give an error.

**Comment by AngryMaciek** [comment]
I confirm that the `rust-src` is not installed alongside other things from conda:
```
ls: XXX/miniconda3/envs/rusttest/lib/rustlib/src/rust: No such file or directory
```
Alright, so I will post an issue on _rust-feedstock_ asking if they could include it.  

However, this may take some time, maybe we could find a workaround meanwhile?  
Would you know what other installation methods of `rust-src` I could try out?

**Comment by bjorn3** [comment]
You can find the tarball at https://static.rust-lang.org/dist/2022-05-19/rust-src-1.61.0.tar.gz Extracting it into XXX/miniconda3/envs/rusttest/ such that XXX/miniconda3/envs/rusttest/lib/rustlib/src/rust exists should work.

**Comment by AngryMaciek** [comment]
@bjorn3 : Thanks, I confirm that this solved the issue :tada:

**Comment by jornfranke** [comment]
Confirm this also works here - using [Mamba](https://github.com/mamba-org/mamba)/Micromamba
