### ISSUE TITLE
Adding local crate causes unresolved import

### ISSUE THREAD

**Issue by dyzdyz010** [evcxr/evcxr#249]
I have a local crate which I want to load into the notebook, I load the crate like this:

```
:dep coordinate_system = { package = "coordinate_system", path = "coordinate_system", version = "*" }
```

The notebook and the crate live side by side so the path is correct I think, and the notebook doesn't complain about the above line.

Then in the next line I use the crate:

```
use coordinate_system;
```

Here the notebook shows an error:

```
[E0432] Error: unresolved import `coordinate_system`
```

**Comment by davidlattimore** [comment]
Hi @dyzdyz010,

I tried to reproduce, but couldn't. Here's what I tried:

```sh
mkdir -p ~/tmp/j8
cd ~/tmp/j8
cargo new --lib coordinate_system
jupyter notebook
```

I then created a new Rust notebook and ran the two lines that you gave.

The only thing that I can think of is that perhaps the kernel got restarted after you ran the `:dep` line and before you ran the `use` line. That would give the error that you got. You could look at the output of the terminal where jupyter notebook is running to see if it mentions the kernel being restarted or anything like that.

**Comment by SichangHe** [comment]
I had the same issue. I solved it by converting my `bin` crate into a `lib` crate.

**Comment by davidlattimore** [comment]
Thanks @SichangHe!. That was the missing bit that I needed to reproduce the problem. I'll add some code to detect adding a dep on a bin crate and give a proper error.
