### ISSUE TITLE
offline mode and rust-analyzer errors on loading multiple dependencies

### ISSUE THREAD

**Issue by kting28** [evcxr/evcxr#265]
On a machine without internet access. `:offline 1` works when there is only 1 `:dep some_crate` loaded. With multiple `:dep`s, it seems rust analyzer's `ra_ap_project_model` dies on 
```
>> :offline 1
Offline mode: true
>> :dep csv     // ok here!
>> :dep rand
Failed to read Cargo metadata from Cargo.toml file <tmp>/.tmpTQ65C4/Cargo.toml, Some(Version { major: 1, minor: 68, patch: 0, pre: Prerelease("nightly") })
```
A single crate is fine. I tracked it down to `CargoWorkspace::fetch_metadata(` but can't seem to find any more hints. There's an open issue on RA regarding being truly offline (https://github.com/rust-lang/rust-analyzer/issues/12499) .

How is `:offline 1` get passed to RA? I checked the temporary `Cargo.toml` file and don't see `net.offline = true`. Do we need to add that so RA gets it?

**Comment by kting28** [comment]
I did a quick strace to see what's going on, it seems on 2nd `:dep` command , it tries to update crates.io index even in offline:
```
poll([{fd=13, events=POLLIN}, {fd=15, events=POLLIN}], 2, 4294967295) = 1 ([{fd=15, revents=POLLIN}])
read(15, "    Updating crates.io index\n", 32) = 29
read(15, 0x2e5af87239d, 3)              = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=13, events=POLLIN}, {fd=15, events=POLLIN}], 2, 4294967295) = 1 ([{fd=15, revents=POLLIN}])
read(15, "err", 3)                      = 3
read(15, "or: failed to get `csv` as a dep", 32) = 32
read(15, "endency of package `ctx v1.0.0 ("..., 64) = 64
read(15, "ng/tmp/.tmpjSkfjx)`\n\nCaused by:\n"..., 128) = 128
read(15, "\n\nCaused by:\n  failed to fetch `"..., 256) = 256
read(15, "g.html#netgit-fetch-with-cli\n\nCa"..., 512) = 135
```

**Comment by davidlattimore** [comment]
Thanks for the report @kting28. I suspect you're right and we're not currently passing anything about offline mode to rust-analyzer. I can't recall what testing I did when I added the offline mode - likely not enough. Your suggestion of adding `net.offline = true` to `Cargo.toml` seems like a good one. If you'd like to have a go at making the change, the function that generates Cargo.toml is `get_cargo_toml_contents` in `module.rs`. You should be able to determine whether offline mode is active by calling `state.offline_mode()`.

**Comment by davidlattimore** [comment]
Oh, there's also code in `validate_dep` that generates a different `Cargo.toml` just for use when a dependency is added.

**Comment by kting28** [comment]
@davidlattimore  sure I'd like to try that but before that I need to make sure RA actually honor that flag. From the issue I included above, it seems RA doesn't care about the `net.offline` flag when fetching meta.

**Comment by kting28** [comment]
I made the change and see the flag set in the temp `Cargo.toml` but RA does not seem to care about it as the same error persists. Do you still want to take a look at a PR for the trivial change?
Regardless, I think there's a typo in the `offline_mode` function as it doesn't need `&mut self` for a read-only return of the offline state flag. Btw, thanks for the amazing tool !

**Comment by kting28** [comment]
After playing around this a bit I found a workaround - setting `CARGO_NET_OFFLINE=true` in the environment resolves the issue - of course this assumes everything is in the cache already. May be the `net.offline` can be set regardless in case in the future upstream RA picks it up.

**Comment by davidlattimore** [comment]
Thanks for looking at all this @kting28. So do you think the `set_offline_mode` function should set `CARGO_NET_OFFLINE`? I'm happy to receive whatever PRs you think make sense, trivial or otherwise.

You're right, that `&mut self` shouldn't need to be `mut`.

**Comment by kting28** [comment]
Done. Please have a look. `net.offline` does work , earlier I just set it in the wrong file (needs to be in .cargo/config.toml, not Cargo.toml )
