### ISSUE TITLE
Compilation errors after panic

### ISSUE THREAD

**Issue by Marcono1234** [evcxr/evcxr#273]
### Version
evcxr-v0.14.2-x86_64-pc-windows-msvc

### Rust version
- `rustc --version`
rustc 1.65.0 (897e37553 2022-11-02)
- `cargo --version`
cargo 1.65.0 (4bc8f24d3 2022-10-20)

### OS
Windows 11 22H2
`ver.exe` output: Microsoft Windows [Version 10.0.22621.1265]

### Description
When a panic occurs while running code with evcxr, any subsequent code fails to compile due to a linking error. The error only happens after a panic occurred; if no panic has occurred yet all code compiles and runs just fine without any issues.
```
A compilation error was found in code we generated.
Ideally this shouldn't happen. Type :last_error_json to see details.
error: linking with `link.exe` failed: exit code: 1201
  |
  = note: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\link.exe" "/DEF:C:\\Users\\#redacted#\\AppData\\Local\\Temp\\rustcBjRlZa\\lib.def" "/NOLOGO" "C:\\Users\\#redacted#\\AppData\\Local\\Temp\\rustcBjRlZa\\symbols.o" "C:\\Users\\#redacted#\\AppData\\Local\\Temp\\.tmpmfgwZy\\target\\x86_64-pc-windows-msvc\\debug\\deps\\ctx.13iojc1x2n48ec7z.rcgu.o" "C:\\Users\\#redacted#\\AppData\\Local\\Temp\\.tmpmfgwZy\\target\\x86_64-pc-windows-msvc\\debug\\deps\\ctx.17zvd30j96363x2j.rcgu.o" "C:\\Users\\#redacted#\\AppData\\Local\\Temp\\.tmpmfgwZy\\target\\x86_64-pc-windows-msvc\\debug\\deps\\ctx.1kart4ysmj1fh3ef.rcgu.o" "C:\\Users\\#redacted#\\AppData\\Local\\Temp\\.tmpmfgwZy\\target\\x86_64-pc-windows-msvc\\debug\\deps\\ctx.1r3gp7v1yfejsydm.rcgu.o" "C:\\Users\\#redacted#\\AppData\\Local\\Temp\\.tmpmfgwZy\\target\\x86_64-pc-windows-msvc\\debug\\deps\\ctx.1rzqn2gpnjqem29q.rcgu.o" "C:\\Users\\#redacted#\\AppData\\Local\\Temp\\.tmpmfgwZy\\target\\x86_64-pc-windows-msvc\\debug\\deps\\ctx.1touxy6isutog6mj.rcgu.o" "C:\\Users\\#redacted#\\AppData\\Local\\Temp\\.tmpmfgwZy\\target\\x86_64-pc-windows-msvc\\debug\\deps\\ctx.20cko02heak4wejk.rcgu.o" "C:\\Users\\#redacted#\\AppData\\Local\\Temp\\.tmpmfgwZy\\target\\x86_64-pc-windows-msvc\\debug\\deps\\ctx.23k458l03p9afiap.rcgu.o" "C:\\Users\\#redacted#\\AppData\\Local\\Temp\\.tmpmfgwZy\\target\\x86_64-pc-windows-msvc\\debug\\deps\\ctx.3eic6igxou3059sb.rcgu.o" "C:\\Users\\#redacted#\\AppData\\Local\\Temp\\.tmpmfgwZy\\target\\x86_64-pc-windows-msvc\\debug\\deps\\ctx.3flk0knhxp4o2k4n.rcgu.o" "C:\\Users\\#redacted#\\AppData\\Local\\Temp\\.tmpmfgwZy\\target\\x86_64-pc-windows-msvc\\debug\\deps\\ctx.414wys5otqy7b7jp.rcgu.o" "C:\\Users\\#redacted#\\AppData\\Local\\Temp\\.tmpmfgwZy\\target\\x86_64-pc-windows-msvc\\debug\\deps\\ctx.4izej08tqf27tkn1.rcgu.o" "C:\\Users\\#redacted#\\AppData\\Local\\Temp\\.tmpmfgwZy\\target\\x86_64-pc-windows-msvc\\debug\\deps\\ctx.4odleb3yrsvkgqrn.rcgu.o" "C:\\Users\\#redacted#\\AppData\\Local\\Temp\\.tmpmfgwZy\\target\\x86_64-pc-windows-msvc\\debug\\deps\\ctx.4tapghq3mgqlud8i.rcgu.o" "C:\\Users\\#redacted#\\AppData\\Local\\Temp\\.tmpmfgwZy\\target\\x86_64-pc-windows-msvc\\debug\\deps\\ctx.55niw4mzcspl59a8.rcgu.o" "C:\\Users\\#redacted#\\AppData\\Local\\Temp\\.tmpmfgwZy\\target\\x86_64-pc-windows-msvc\\debug\\deps\\ctx.yyycq2qb9vu8jkp.rcgu.o" "/LIBPATH:C:\\Users\\#redacted#\\AppData\\Local\\Temp\\.tmpmfgwZy\\target\\x86_64-pc-windows-msvc\\debug\\deps" "/LIBPATH:C:\\Users\\#redacted#\\AppData\\Local\\Temp\\.tmpmfgwZy\\target\\debug\\deps" "/LIBPATH:C:\\Users\\#redacted#\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "/LIBPATH:C:\\Users\\#redacted#\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "std-fdaa63d6970be740.dll.lib" "C:\\Users\\#redacted#\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-3f507ba7adac1c2a.rlib" "kernel32.lib" "advapi32.lib" "userenv.lib" "kernel32.lib" "ws2_32.lib" "bcrypt.lib" "msvcrt.lib" "legacy_stdio_definitions.lib" "/NXCOMPAT" "/LIBPATH:C:\\Users\\#redacted#\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "/OUT:C:\\Users\\#redacted#\\AppData\\Local\\Temp\\.tmpmfgwZy\\target\\x86_64-pc-windows-msvc\\debug\\deps\\ctx.dll" "/OPT:REF,ICF" "/DLL" "/IMPLIB:C:\\Users\\#redacted#\\AppData\\Local\\Temp\\.tmpmfgwZy\\target\\x86_64-pc-windows-msvc\\debug\\deps\\ctx.dll.lib" "/DEBUG" "/NATVIS:C:\\Users\\#redacted#\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\#redacted#\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\#redacted#\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/NATVIS:C:\\Users\\#redacted#\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libstd.natvis" "-fuse-ld=lld"
  = note: Non-UTF-8 output: LINK : warning LNK4044: Nicht erkannte Option /fuse-ld=lld; wird ignoriert.\r\nLINK : fatal error LNK1201: Fehler beim Schreiben in die Programmdatenbank \"C:\\Users\\#redacted#\\AppData\\Local\\Temp\\.tmpmfgwZy\\target\\x86_64-pc-windows-msvc\\debug\\deps\\ctx.pdb\"\". M\x94glicherweise ist nicht gen\x81gend Festplattenspeicher verf\x81gbar, ist der Pfad ung\x81ltig oder reichen die Zugriffsrechte nicht aus.\r\n
```

Unfortunately some of these messages are in German, but I will try to translate them below (I don't know the exact wording of the English message variant though):
- > Nicht erkannte Option /fuse-ld=lld; wird ignoriert

  Unrecognized option `/fuse-ld=lld`; is ignored
- > Fehler beim Schreiben in die Programmdatenbank

  Error while writing into the program database
- > M\x94glicherweise ist nicht gen\x81gend Festplattenspeicher verf\x81gbar, ist der Pfad ung\x81ltig oder reichen die Zugriffsrechte nicht aus

  Possibly too little disk space is available, the path is invalid or the access permissions don't suffice

### Reproduction steps
1. Start `evcxr.exe`
2. Type the following Rust code and press <kbd>Enter</kbd>
    ```rust
    panic!("test")
    ```
3. Type the following Rust code and press <kbd>Enter</kbd>
    ```rust
    let r = 1;
    ```
    :x: Bug: The compilation error occurs

Interestingly, if after step 2 or 3 you write again `panic!("test")`, the following error is shown:
> [unreachable_code] Error: unreachable expression

Maybe that gives a hint what the underlying issue might be?

**Comment by davidlattimore** [comment]
Thanks @Marcono1234.  I think the key is the mention of `ctx.pdb` in the error message. When evcxr compiles each bit of code, it does so as a crate called `ctx`. It then renames the resulting `.dll` file (or equivalent on other platforms). It seems that on Windows a `.pdb` file is being written as well. Evcxr doesn't rename the `.pdb` file. I guess when the panic occurs, something in Rust's runtime is opening the `.pdb` file and is keeping it open, causing the file to be locked. When we then try to compile again, we can't rewrite `ctx.pdb` because it's still locked.

This was a bit of a surprise, since we set `debug = false` in Cargo.toml - but apparently this doesn't actually disable emitting of debug info. For that, we need to pass the argument `-Clink-arg=/DEBUG:NONE`.

**Comment by bjorn3** [comment]
> This was a bit of a surprise, since we set debug = false in Cargo.toml - but apparently this doesn't actually disable emitting of debug info.

You need `strip = "debuginfo"` for that. Otherwise debuginfo from the standard library will still end up in your binary (on unix) or in a .pdb file (on windows)

**Comment by davidlattimore** [comment]
Thanks @bjorn3. That's a better fix. I recently acquired an old laptop with Windows on it, so I was even able to try it out.

**Comment by Marcono1234** [comment]
Thanks to both of you! That seems to have fixed the issue.
