### ISSUE TITLE
`:toolchain` doesn't work

### ISSUE THREAD

**Issue by DerickEddington** [evcxr/evcxr#284]
```
$ realpath $(which cargo)
/nix/store/zlk7dd75c9jliiycrn7wf9xlzhsswrsx-rustup-1.25.2/bin/rustup

$ cargo +nightly --version
cargo 1.70.0-nightly (4a3c588b1 2023-03-14)

$ ./target/release/evcxr
Welcome to evcxr. For help, type :help
>> :version
0.14.2

>> :toolchain nightly
Toolchain: nightly

>> let x = 1;
Compilation failed, but no parsable errors were found. STDERR:
error: no such command: `+nightly`

	Cargo does not handle `+toolchain` directives.
	Did you mean to invoke `cargo` through `rustup` instead?

STDOUT:

>> 

$ git log -n1 --format=oneline
b7f5f9b80bb77b77eb9e04eec55a6a61cf4b2862 Add missing commands to COMMON.md
```

Looks like this is due to `Config::cargo_path` [being initialized](https://github.com/evcxr/evcxr/blob/b7f5f9b80bb77b77eb9e04eec55a6a61cf4b2862/evcxr/src/eval_context.rs#L124) to a specific executable (which doesn't support the `+toolchain` argument), as determined by [`rustup_cargo_path`](https://github.com/evcxr/evcxr/blob/b7f5f9b80bb77b77eb9e04eec55a6a61cf4b2862/evcxr/src/eval_context.rs#L1831-L1850).  Maybe that field should be updated when `:toolchain ...` is invoked?

**Comment by davidlattimore** [comment]
Thanks for reporting that @DerickEddington. You're right. I'd say it's almost certain that I broke it with [this commit](https://github.com/evcxr/evcxr/commit/38a67c9c0ab38c8a63397faf68105a4949ab9fd1). It hopefully shouldn't be too hard to fix.

**Comment by davidlattimore** [comment]
I've pushed a fix to the main branch on github
