### ISSUE TITLE
It stucks when trying to add a dependency

### ISSUE THREAD

**Issue by felipelalli** [evcxr/evcxr#285]
I'm trying to do it:

`:dep chrono = "0.4.23"`

but it hangs up and don't show any visual feedback. I tried to turn off my VPN, quit and back, reset configuration, clear with ":clear" but nothing seems to work.

Version 0.14.2 from asdf.

**Comment by davidlattimore** [comment]
What do you mean "hangs up"? It's expected that it won't show any visual feedback until it has finished compiling the `chrono` crate. Depending on the speed of your system, that could take a while. If you leave it for a bit, perhaps it will eventually finish? Or does it actually exit from evcxr.

**Comment by felipelalli** [comment]
After ~20 min it has finished. Thank you! I found a duplicated here: #224

**Comment by davidlattimore** [comment]
Wow, 20 minutes seems a bit more than I would have expected. On my laptop it takes about 8 seconds. I wonder if something is going wrong. If you create a crate that depends on chrono, does it take ages to build? e.g.

```bash
cargo new foo
cd foo
cargo add chrono
cargo build
```

**Comment by felipelalli** [comment]
Hi @davidlattimore ! I'm not sure why it took so long, but maybe some Internet / connection issue? Or my computer was under heavy CPU work? I'm under a VPN. I tried other deps like "json" and it took only few seconds.

I tried what you asked now and I got:

```
➜  tmp cargo new foo
     Created binary (application) `foo` package
➜  tmp cd foo 
➜  foo git:(master) ✗ time cargo add chrono
    Updating crates.io index
      Adding chrono v0.4.24 to dependencies.
             Features:                                       
             + clock
             + iana-time-zone
             + js-sys
             + oldtime
             + std
             + time
             + wasm-bindgen
             + wasmbind
             + winapi
             - __doctest
             - __internal_bench
             - alloc
             - arbitrary
             - criterion
             - libc
             - pure-rust-locales
             - rkyv
             - rustc-serialize
             - serde
             - unstable-locales
cargo add chrono  3,21s user 0,59s system 33% cpu 11,426 total
➜  foo git:(master) ✗ time cargo build     
  Downloaded iana-time-zone v0.1.55
  Downloaded 1 crate (19.5 KB) in 1.75s
   Compiling autocfg v1.1.0
   Compiling libc v0.2.140
   Compiling iana-time-zone v0.1.55
   Compiling num-traits v0.2.15
   Compiling num-integer v0.1.45
   Compiling time v0.1.45
   Compiling chrono v0.4.24
   Compiling foo v0.1.0 (/home/felipelalli/tmp/foo)
    Finished dev [unoptimized + debuginfo] target(s) in 6.60s
cargo build  8,53s user 2,62s system 164% cpu 6,775 total
```

I tried:

`>> :dep chrono = "0.4.23"`

again now with my computer idle it took "only" 20 seconds. I guess it was some Internet or CPU issue at that time because I was making a very intensive usage of my computer in a project I am working.

Thank you anyway!

**Comment by bjorn3** [comment]
It could also be that cargo was updating the registry. By default this is done by cloning a repo from github. Given how much crates.io has grown, this now takes quite a while when your local clone hasn't been updated for a while. Since rustc 1.68 it is now possible to switch to the sparse registry protocol which only downloads the parts that are actually necessary rather than everything. This is much faster. Rustc 1.70 is expected to use the sparse registry protocol by default. https://blog.rust-lang.org/2023/03/09/Rust-1.68.0.html#cargos-sparse-protocol
