### ISSUE TITLE
println! does not preserve the order of lines

### ISSUE THREAD

**Issue by dclong** [evcxr/evcxr#305]
When printing using `println!` in a loop, the order of lines are not preserved. This is very annoying. Is there any way to evcxr_jupyter respect the order of `println!`?

**Comment by davidlattimore** [comment]
Weird. I'd expect that `println!` and `eprintln!` might not come out in the same order as each other, but I would have thought that all the output from `println!` should be in a consistent order. Do you have code that reproduces this?

**Comment by davidlattimore** [comment]
Thanks. I've pushed a fix to github if you'd like to give it a try
