### ISSUE TITLE
Output error with comment.

### ISSUE THREAD

**Issue by baiguoname** [evcxr/evcxr#306]
This if fine:
![image](https://github.com/evcxr/evcxr/assets/52092777/6ef3908a-65c9-4fd8-b26b-9c183416b983)
But this has error:
![image](https://github.com/evcxr/evcxr/assets/52092777/78d57169-b1c2-4063-bd44-1c2d95902270)

**Comment by davidlattimore** [comment]
Thanks for the report. I've pushed a commit to the repo which should fix this.

**Comment by baiguoname** [comment]
I just test the newest code, it works fine now. Thanks very much.
