### ISSUE TITLE
`init.evcxr` and `prelude.rs` placed in the suggested MacOS location doesn't seem to do anything

### ISSUE THREAD

**Issue by anandijain** [evcxr/evcxr#314]
Hello, and thank you for the amazing crate.

I'm confused about the directions in COMMON.md, which recommends mac users create a file `/Users/anand/Library/Preferences/evcxr/init.evcxr` and `prelude.rs`

After placing :sccache 1 and a local dependence in the init file and a simple variable assignment in prelude, it doesn't seem that it gets looked at or loaded. I don't see any message like `Executing prelude from "~/.config/evcxr/prelude.rs"` as shown in COMMON.md. 

Is there something else I missed?

**Comment by davidlattimore** [comment]
Perhaps the configuration directory is different for some reason. You could try doing something similar to what evcxr does to locate the config dir. e.g.

```rust
:dep dirs
dirs::config_dir().unwrap().join("evcxr").join("init.evcxr")
```

**Comment by anandijain** [comment]
```rust
anand@Loris-Air ~/.r/d/my_cas (main)> evcxr
Welcome to evcxr. For help, type :help
>> :dep dirs
dirs::config_dir().unwrap().join("evcxr").join("init.evcxr")
   Compiling libc v0.2.147
   Compiling dirs v5.0.1
"/Users/anand/Library/Application Support/evcxr/init.evcxr"
```
Ah okay it's `/Users/anand/Library/Application Support/evcxr/init.evcxr`. 

Nice 
```
anand@Loris-Air ~/L/A/evcxr> evcxr
Welcome to evcxr. For help, type :help
Startup commands will be loaded from /Users/anand/Library/Application Support/evcxr/init.evcxr
Prelude will be loaded from /Users/anand/Library/Application Support/evcxr/prelude.rs
```
