### ISSUE TITLE
Listing current REPL deps and manifest from within REPL?

### ISSUE THREAD

**Issue by anandijain** [evcxr/evcxr#315]
In Julia, it's really nice to be able to see the current dependencies within the repl with `]status` and to see the manifest `]status -m`. Is this possible for evxcr? 

Thanks!

**Comment by davidlattimore** [comment]
There's nothing currently that does that, but I'd be happy to take PRs to add it as a feature.

If you'd like to try, the place to add new commands is `create_commands` in `command_context.rs`.

The current dependencies can be found in `ContextState::external_deps` (`eval_context.rs`).
