### ISSUE TITLE
Is it possible to print out the documentation?

### ISSUE THREAD

**Issue by baiguoname** [evcxr/evcxr#321]
For example, I have `struct`,  which has a documentation:
```
///this is my struct
struct MyStruct;
```
Is there a way I can print out the documentation this:
![image](https://github.com/evcxr/evcxr/assets/52092777/0eba45ba-ed19-49c7-a4a7-d25ff06cab22)

**Comment by davidlattimore** [comment]
There isn't currently, but it's a good idea. Not sure when I'd be likely to get to it though, so if you or anyone else would like to have a try at implementing it let me know and I'll try to provide some guidance

**Comment by baiguoname** [comment]
I have tried to read `HOW_IT_WORKS.md` and source code several times before, but by lack of familiarity with rust,  the `command_context.rs` is still like a magic to me for now. Could you give me path of learning how it works? Before I read the source code, should I know the detail of how `rust-analyzer` works?

**Comment by davidlattimore** [comment]
Yep, I suspect most of the work would likely be figuring out how to get the information out of rust-analyzer.

The evcxr code that uses rust-analyzer is in `rust_analyzer.rs`. Having a look through that is probably worthwhile to see how it's working.

Looking at rust-analyzer, I think the code that shows documentation is in [hover/render.rs](https://docs.rs/crate/ra_ap_ide/latest/source/src/hover/render.rs)

There's two options I can see.

1) Generate some rust code containing the snippet that's after the `:doc` command, then call [Analysis::hover](https://github.com/rust-lang/rust-analyzer/blob/b9a9722bda8f1ff7d8691701b98a753f74e70c06/crates/ide/src/lib.rs#L461)
2) Query the definition of `MyStruct` using something like `Semantics::resolve_path` then call some other methods to get the docs from the definition.

**Comment by davidlattimore** [comment]
Another useful thing to look at would be how completions work. In particular, look at the `completions` method in `eval_context.rs`. I suspect integration with hover could work in a similar way.

If you have any questions, do ask.

**Comment by baiguoname** [comment]
I write a method `hover_info` righter after the mothond `completions` of `RustAnalyzer` in `rust_analyzer.rs`:
![图片](https://github.com/evcxr/evcxr/assets/52092777/4347e8ff-40e0-4477-a025-b6712d915470)
And the I try to what can I get from this method in `eval_context.rs`, like this:
![图片](https://github.com/evcxr/evcxr/assets/52092777/dfaa41ea-46f9-4627-9088-1b285b928bf0)
The input code is this:
![图片](https://github.com/evcxr/evcxr/assets/52092777/50581f09-7bd0-4bfb-8c26-0f9659af7e28)
But the `hover_info` can't` get anything, while method `completion`  works fine. I cann't figure it out, can you give me a clue?

**Comment by davidlattimore** [comment]
Maybe use `code.user_offset_to_output_offset(offset)` like is done in `completions`. If you use that for the start and end of the identifier that you're trying to get the hover for, then hopefully you'll end up with offsets that rust-analyzer will be able to make use of.

Have a look at the `completions` method in `eval_context.rs`, which calls `completions` in `rust_analyzer.rs`. The one in `eval_context.rs` does stuff like calling `self.analyzer.set_source(code.code_string())?;` which is important for making sure you're analyzing the code that the user wrote.

**Comment by baiguoname** [comment]
I made a pr to this, but for now the code can just show the documentation as style of plain text. But I saw the error output in jupyter can show in a way of markdown style. Can you give me a guidance how can I get that? Should I learn how the crate `evcxr_jupyter` works, or I can acheive that just in crate `evcxr`?

**Comment by davidlattimore** [comment]
Just wanted to say, nice work implementing this @baiguoname, it's a neat feature! ([PR](https://github.com/evcxr/evcxr/pull/323))
