### ISSUE TITLE
The error doesn't print as expected.

### ISSUE THREAD

**Issue by baiguoname** [evcxr/evcxr#324]
If I have the following inputs in Jupyter:
![image](https://github.com/evcxr/evcxr/assets/52092777/bd69d667-19f8-45c5-83a0-2b9d2fe9726b)
the `undefined_function` is an undefined function. The former's error is normal, but the latter has a more confusional error. I found if I call `eval_context.check` before `eval_context.eval_with_callback` in `eval_context`'s method `eval_with_state`, it will make sure the error to be the former:
![image](https://github.com/evcxr/evcxr/assets/52092777/7a27bdae-404f-4642-bb69-8701d7f6399a)
And the check method alone takes about 20ms.
Is the above method a good way to do it?

**Comment by davidlattimore** [comment]
Nice find! I think calling `check` is reasonable, but it should probably be done deeper down and only if we get an error from `fix_variable_types`. So the logic would be something like:

* If `fix_variable_types` returns an error:
  * Call `check`.
    * If `check` returns a non-empty list of compilation errors, then return `Err(Error::CompilationErrors(...))`
    * Otherwise, return the error that `fix_variable_types` reported

Would you like to have a go at making the change? If not, I'll do it.

**Comment by baiguoname** [comment]
I'm glad to make a try by following your logic, if I can't figure it out as soon as possible, then I'll tell you that.
