### ISSUE TITLE
Slow execution speed

### ISSUE THREAD

**Issue by zxcqirara** [evcxr/evcxr#333]
There is my code:
```rs
fn main() {
	evcxr::runtime_hook();

	let start = Instant::now();
	let (mut context, outputs) = EvalContext::new().unwrap();
	context.eval("let mut s = String::new();").unwrap();
	context.eval(r#"s.push_str("Hello, ");"#).unwrap();
	context.eval(r#"s.push_str("World!");"#).unwrap();
	context.eval(r#"println!("{}", s);"#).unwrap();

	if let Ok(line) = outputs.stdout.recv() {
		println!("{line}\nElapsed: {}ms", start.elapsed().as_millis());
	}
}
```

In release mode it executes in 5.5sec and in debug mode as much as **60sec**
![image](https://github.com/evcxr/evcxr/assets/36239195/4ee4dec6-228a-4d4e-868a-f25fae34a348)
![image](https://github.com/evcxr/evcxr/assets/36239195/3060217f-cce6-4890-8388-f5f67c4c3a7a)

**Comment by bjorn3** [comment]
What is the performance of creating `EvalContext` once and then measuring trying to run something with it several times? Every time you create a new `EvalContext`, rust-analyzer has to analyze the standard library source again for inferring types of local variables inside the user code. This analysis is done on the first `.eval()` call and cached within the `EvalContext`.

**Comment by zxcqirara** [comment]
Understood, didn't think that dev mode can so slowdown evcxr performance
