### ISSUE TITLE
Native file rust cell support

### ISSUE THREAD

**Issue by feribg** [evcxr/evcxr#342]
Currently the python jupyter frontend supports a somewhat overlooked features which is actually very useful to avoid all the crappy notebook + git workarounds:
https://code.visualstudio.com/docs/python/jupyter-support-py#_jupyter-code-cells

This allows to basically have a full python file that can be ran top to bottom as cells but also as a standalone file and not have to deal with the ipynb format issues / state / version control. 

I think will be hugely useful to something like excvr, is this just a matter of updating the vscode extension and adding support for a new rust file type or it requires deeper integration ?

**Comment by davidlattimore** [comment]
I guess one tricky thing about this is the extent to which the input to evcxr differs from regular Rust code. In the case of Python, you can have a Python file with statements directly at the top level and that's valid. However with Rust, you have to put statements inside a function. So I think if you had a .rs file with something like the following, some Rust tooling would say that it's invalid even though it would be a valid cell to pass to evcxr.

```rust
# %%
println!("Hello, world!");
```

**Comment by feribg** [comment]
Yes but that can be worked around somewhat, i guess you can still have the file wrapped in a big `main ()` and have each cell be a commented code snippet within the main which gets around that limitation and still somewhat works. I think you still have to probably tweak some things like magics and the fact rust uses // and not # but those seem entirely frontend (ie not protocol related).

**Comment by davidlattimore** [comment]
That's true. So if the file is a valid Rust file that rustc can understand directly, then I guess that means the work required would just be in some vscode extension. Perhaps the existing extension that's looking for code cells in Python files could be adapted to look for similar annotations in a Rust file. The comment format might need to be different, since Rust uses `//` rather than `#` for comments.

**Comment by feribg** [comment]
Doesn't look unwieldy but for someone with 0 knowledge of the VsCode architecture and 0 tolerance of JS it's a steep hill to climb:
https://github.com/search?q=repo%3Amicrosoft%2Fvscode-jupyter%20%25%25&type=code

**Comment by feribg** [comment]
Upvote here:
https://github.com/microsoft/vscode-jupyter/issues/273
