### ISSUE TITLE
Example from readme with reference to local variables do not work

### ISSUE THREAD

**Issue by Mart-Bogdan** [evcxr/evcxr#344]
**Version** 0.16.0
**rustc** 1.74.0 (79e9716c9 2023-11-13)

[Example](https://github.com/evcxr/evcxr/blob/main/COMMON.md#references) from `COMMON.md` doesn't work.

Example says that trick with Box::leak should work, but it doesn't.
Readme says:
> If you really need `some_values` to persist, you can make `all_values` into a static reference by
leaking it:
> 
> ```rust
> let all_values = Box::leak(Box::new(vec![10, 20, 30, 40, 50]));
> let some_values = &all_values[2..3];
> ```
But if I run it, I'm getting error:
```bash
[winnie@bm-linux-nitro517 ~]$ evcxr
Welcome to evcxr. For help, type :help
>> let all_values = Box::leak(Box::new(vec![10, 20, 30, 40, 50]));
let some_values = &all_values[2..3];
[E0502] Error: cannot borrow `*all_values` as mutable because it is also borrowed as immutable
   ╭─[command:1:1]
   │
 2 │ let some_values = &all_values[2..3];
   │                    ─────┬────  
   │                         ╰────── immutable borrow occurs here
───╯
>> 
>> :version
0.16.0

>> :quit
```

**Comment by davidlattimore** [comment]
Thanks for noticing that.

If we give the variable a type to force it to be a shared reference rather than a mutable reference, then it works.

```rust
let all_values: &'static Vec<i32> = Box::leak(Box::new(vec![10, 20, 30, 40, 50]));
let some_values = &all_values[2..3];
```

I've fixed that bit of documentation so that the example now works.

**Comment by Mart-Bogdan** [comment]
Thanks.
