### ISSUE TITLE
how to trigger code auto completion

### ISSUE THREAD

**Issue by naijim** [evcxr/evcxr#348]
In vscode:

```
:allow_static_linking 1
:dep polars = {version = "0.35.4", features = ["describe"]}

use polars::prelude::*;
use std::fs::File;
use polars::datatypes::DataType;

let schema = Schema::from_iter(vec![
    Field::new("id", DataType::Utf8),
]);
```

While I type `Schema`, is it possible to trigger code auto completion of `from_iter`? I type `::`, but no auto completion.
Is there anything I should install to get this feature like in a normal vscode rust file?

**Comment by davidlattimore** [comment]
I've never actually tried the vscode Jupyter integration, although I'm pretty sure it supports less than the web interface.

Does it work if you just try completing names in `std` without loading polars? e.g. `std::path::Path`

**Comment by naijim** [comment]
not working while trying `std`.
I will create an issue for vscode extension.
