### ISSUE TITLE
Trying to include a local package gives a manifest error

### ISSUE THREAD

**Issue by feribg** [evcxr/evcxr#357]
```
evcxr --version                                                                            ✔ │ base 🐍 │ 16:06:49 
evcxr_repl 0.16.0
```
then doing:
`:dep rndmwlk = {path= ... }`

the dep builds fine but trying to use it gives:

```
[E0786] Error: found invalid metadata files for crate `...`
```

The crate works fine locally when included form a different project as well as in `IRust` repl which as far as i know is based on evcxr ? What is the reason for that, does evcxr ignore the system rust compiler and that causes a version mismatch for the manifest or ?

**Comment by davidlattimore** [comment]
It looks like you might have meant to do the following:

```
:dep rndmwlk = {path= ".." }
```

with two dots rather than three and with the path enclosed in double-quotes

**Comment by davidlattimore** [comment]
irust isn't based on evcxr BTW

**Comment by feribg** [comment]
no the path was just an example, as I mentioned it detected and built the
package as it's supposed to. Once intry to use it it fails on the use
clause.

**Comment by davidlattimore** [comment]
Does this problem occur for any crate that you try to use, or just a specific crate?

I just tried the following, which worked for me:

```sh
cargo new --lib foo1
```

Then in evcxr:

```
:dep foo1 = { path = "foo1" }
use foo1;
foo1::add(5, 4)
```

**Comment by feribg** [comment]
Does the file system path matter, I did rename the package folder from xyz -> xyz_rs but everything else is correct I did run cargo clean too, I’m not sure if there’s any other caches etc ?

**Comment by feribg** [comment]
@davidlattimore thanks, this fixed it! i dont know if this helps but i have this in my toml:
```
[lib]
name = "rndmwlk"
crate-type = ["cdylib", "rlib"]
```
I also have some dependencies on linear algebra and custom build.rs to change the blas library based on the OS.
