### ISSUE TITLE
Problem converting a Vec to a &[] struct

### ISSUE THREAD

**Issue by Rafael-Julio-2242** [evcxr/evcxr#372]
There is a completly valid way of converting any type of Vec structure in Rust to a &[].

Exemple: 
```
let test = vec![1,2,4]; `
let test_as_slice = test.as_slice();
                  
println!("{:?}", test_as_slice);
```
This works in vscode inside a normal main function, but, when using jupyter notebook, appears a errror to me

![image](https://github.com/evcxr/evcxr/assets/140743082/3b074164-453a-4784-ab75-76008521df77)

I am curious about why it happen's, if i am doing something wrong i would love to learn more about. I am interested in Rust and i am still learning things about how things work

**Comment by bjorn3** [comment]
Each variable is moved into a global HashMap with all variables at the end of the cell and then moved back into the next cell if it is used. This invalidates any outstanding references to the variable. It should work if you did

```rust
let test = vec![1,2,4];
{
    let test_as_slice = test.as_slice();
                  
    println!("{:?}", test_as_slice);
}
```

to limit the scope of `test_as_slice` such that it isn't stored in the variables HashMap.
