### ISSUE TITLE
cargo install evcxr_jupyter failed

### ISSUE THREAD

**Issue by mingerfan** [evcxr/evcxr#384]
I try to use cargo install to install evcxr_jupyter, but it failed.
![图片](https://github.com/user-attachments/assets/690bc10e-d995-4d13-b97d-7dafe6be24d1)
Then I try to install it from source, failed again, with the same reason.
It seems that zeromq has some compatibility problems in the rustc 1.81.0

**Comment by davidlattimore** [comment]
Thanks for the report. Can you try `cargo install --locked evcxr_jupyter` and see if that works for you?

**Comment by davidlattimore** [comment]
0.4.1 of the zeromq crate is now released with a fix for this, so it should now install even without `--locked`.

**Comment by boredstiff** [comment]
@davidlattimore I just went through installing evcxr_jupyter for the first time and had to use `--locked` to get past the same error in the screenshot.

**Comment by davidlattimore** [comment]
I've updated the relevant dependencies and pushed version 0.18.0 to crates.io.

**Comment by mingerfan** [comment]
cc
